---
- name: Setup nginx
  hosts: demo
  user: "{{ user }}"

  vars_files:
    - defaults/main.yml
    - vars.yml

  handlers:
    - include: handlers/main.yml

  tasks:
    - name: Clone the repo
      git: repo={{ item.repo }} dest={{ folder }}/{{ item.name }}
      with_items: "{{ projects }}"
      register: repo

    - name: Setup vhosts
      template: src=templates/nginx_server.j2 dest={{nginx_conf_dir}}/sites-available/{{ item.name }}.conf
      with_items: "{{ projects }}"
      sudo: yes

    - name: Create links for sites-enabled
      file: state=link src={{ nginx_conf_dir }}/sites-available/{{ item.name }}.conf dest={{ nginx_conf_dir }}/sites-enabled/{{ item.name }}.conf
      with_items: "{{ projects }}"
      sudo: yes
      notify:
       - reload nginx

    - name: Install npm packages
      shell: source {{ folder }}/.nvm/nvm.sh && npm install # Workaround for nvm
      args:
        chdir: ~/{{ item.name }}
        executable: /usr/bin/zsh
      when: repo.changed
      with_items: "{{ projects }}"

    - name: Start app
      shell: source {{ folder }}/.nvm/nvm.sh && forever start --sourceDir . --workingDir . -c "npm start" .
      args:
        chdir: ~/{{ item.name }}
        executable: /usr/bin/zsh
      when: repo.changed
      with_items: "{{ projects }}"

    - name: Print info
      debug: msg="{{ item.name }} is running on port {{ item.port }} and its static files should be located at {{ folder }}/{{ item.name }}. The project is accessible at {{ item.name }}.{{ domain }}"
      with_items: "{{ projects }}"
